a ,b,c=input().split()
a=int(a)
b=int(b)
c=int(c)
print ("No of Pizzas:",a)
print("No of Puffs:",b)
print("No of Cold Drinks:",c)
total =(100*a)+(20*b)+(10*c)
print("Total price =",total)
print("ENJOY THE SHOW!!!")
